//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reingenia.planificador.webadmin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class authentication {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal authentication() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("reingenia.planificador.webadmin.Resources.authentication", typeof(authentication).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresar.
        /// </summary>
        public static string login_form_botoningresar {
            get {
                return ResourceManager.GetString("login_form_botoningresar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valide los siguientes errores:.
        /// </summary>
        public static string login_form_errors {
            get {
                return ResourceManager.GetString("login_form_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, ingrese los datos de su cuenta de usuario y contraseña para acceder al sistema.
        /// </summary>
        public static string login_form_information {
            get {
                return ResourceManager.GetString("login_form_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Mantener la sesión iniciada?.
        /// </summary>
        public static string login_form_mantenersesionlabel {
            get {
                return ResourceManager.GetString("login_form_mantenersesionlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contraseña.
        /// </summary>
        public static string login_form_placeholderpassword {
            get {
                return ResourceManager.GetString("login_form_placeholderpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario.
        /// </summary>
        public static string login_form_placeholderusername {
            get {
                return ResourceManager.GetString("login_form_placeholderusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inicio de sesión.
        /// </summary>
        public static string login_form_title {
            get {
                return ResourceManager.GetString("login_form_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to información no válida para contraseña.
        /// </summary>
        public static string login_model_datatypepassword {
            get {
                return ResourceManager.GetString("login_model_datatypepassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingrese la contraseña.
        /// </summary>
        public static string login_model_requiredpassword {
            get {
                return ResourceManager.GetString("login_model_requiredpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ingrese el nombre de usuario.
        /// </summary>
        public static string login_model_requiredusername {
            get {
                return ResourceManager.GetString("login_model_requiredusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to información no válida para contraseña.
        /// </summary>
        public static string login_model_stringlengthpassword {
            get {
                return ResourceManager.GetString("login_model_stringlengthpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to información no válida para nombre de usuario.
        /// </summary>
        public static string login_model_stringlengthusername {
            get {
                return ResourceManager.GetString("login_model_stringlengthusername", resourceCulture);
            }
        }
    }
}
