//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace reingenia.planificador.webadmin.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class webadmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal webadmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("reingenia.planificador.webadmin.Resources.webadmin", typeof(webadmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asigna, evalua las tareas designadas.
        /// </summary>
        public static string sistema_descripcion {
            get {
                return ResourceManager.GetString("sistema_descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REINGENIA GS.
        /// </summary>
        public static string sistema_empresa {
            get {
                return ResourceManager.GetString("sistema_empresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planificador de tareas.
        /// </summary>
        public static string sistema_nombre {
            get {
                return ResourceManager.GetString("sistema_nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambiar mi password.
        /// </summary>
        public static string useroptions_cambiarpassword {
            get {
                return ResourceManager.GetString("useroptions_cambiarpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        public static string useroptions_cerrarsesion {
            get {
                return ResourceManager.GetString("useroptions_cerrarsesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mi perfil.
        /// </summary>
        public static string useroptions_miperfil {
            get {
                return ResourceManager.GetString("useroptions_miperfil", resourceCulture);
            }
        }
    }
}
